.PHONY:clean

CC=gcc
CFLAGS=-Wall -g

BIN=minsh
OBJS=main.o parse.o init.o execute.o buildin.o

$(BIN):$(OBJS)
	$(CC) $(CFLAGS) $^ -o $@
%.o:%.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f *.o $(BIN)
