#子Makefile模板
#子目标 .h 库 包含公有Makefile

EXE = complicated
LIBS = 

INCLUDE_DIRS = $(ROOT)/code/array/inc $(ROOT)/code/foo/inc $(ROOT)/code/hello/inc
LINK_LIBS = array foo hello
include $(ROOT)/build/MakefileRule
